window.talrivoCatalog = [
  {
    model: "G941",
    name: "Tri-Mode ANC Gaming Headset",
    category: "wireless",
    label: "Wireless + ANC",
    summary: "Wireless gaming direction with ANC option and 50 mm driver configuration.",
    specs: ["2.4 GHz configuration", "50 mm driver option", "20 Hz - 20 kHz"],
    images: ["image-01.jpg", "image-02.jpg", "image-03.jpg", "image-04.jpg", "image-05.jpg", "image-06.jpg", "image-07.jpg", "image-08.jpg"],
    folder: "g941-wireless",
    video: null
  },
  {
    model: "G940",
    name: "Low-Latency Wireless Gaming Headset",
    category: "wireless",
    label: "Wireless",
    summary: "Compact wireless gaming model for retail and private-label assortment planning.",
    specs: ["2.4 GHz configuration", "40 mm driver option", "20 ms latency listed"],
    images: ["image-01.jpg", "image-02.jpg", "image-03.jpg", "image-04.jpg", "image-05.jpg", "image-06.jpg", "image-07.jpg"],
    folder: "g940-wireless",
    video: null
  },
  {
    model: "G942",
    name: "2.4G Wireless Gaming Headset",
    category: "wireless",
    label: "Wireless",
    summary: "Over-ear gaming headset with wireless receiver concept for multiple gaming channels.",
    specs: ["2.4 GHz configuration", "50 mm driver option", "OEM discussion available"],
    images: ["image-01.png", "image-02.png", "image-03.png", "image-04.jpg"],
    folder: "g942-wireless",
    video: null
  },
  {
    model: "G923",
    name: "Wireless Gaming Headset",
    category: "wireless",
    label: "Wireless",
    summary: "Gaming headset option for buyers comparing price-driven wireless assortments.",
    specs: ["2.4 GHz configuration", "40 mm driver option", "Video candidate available"],
    images: ["image-01.jpg", "image-02.jpg", "image-03.jpg", "image-04.jpg"],
    folder: "g923-wireless",
    video: null
  },
  {
    model: "G920",
    name: "Wireless Gaming Headset",
    category: "wireless",
    label: "Wireless",
    summary: "Gaming product direction with product demonstration footage available for review.",
    specs: ["2.4 GHz configuration", "40 mm driver option", "Video candidate available"],
    images: ["image-01.jpg", "image-02.jpg", "image-03.jpg"],
    folder: "g920-wireless",
    video: null
  },
  {
    model: "G936",
    name: "Wireless Gaming Headset",
    category: "wireless",
    label: "Wireless",
    summary: "Wireless headset presentation model with folding demonstration footage available.",
    specs: ["Specification on request", "Private-label discussion", "Video candidate available"],
    images: ["image-01.jpg", "image-02.jpg", "image-03.jpg"],
    folder: "g936-wireless",
    video: null
  },
  {
    model: "G939",
    name: "Wireless Gaming Headset",
    category: "wireless",
    label: "Wireless",
    summary: "50 mm driver direction within the wireless gaming supply range.",
    specs: ["2.4 GHz configuration", "50 mm driver option", "Commercial terms on request"],
    images: ["image-01.jpg", "image-02.jpg", "image-03.jpg", "image-04.jpg"],
    folder: "g939-wireless",
    video: null
  },
  {
    model: "G927",
    name: "Wireless Gaming Headset",
    category: "wireless",
    label: "Wireless",
    summary: "Wireless gaming visual direction with product demonstration video prepared for buyer review.",
    specs: ["2.4 GHz direction", "Specification sheet on request", "Video candidate available"],
    images: ["image-01.jpg", "image-02.jpg", "image-03.jpg"],
    folder: "g927-wireless",
    video: null
  },
  {
    model: "G926",
    name: "Wireless Gaming Headset",
    category: "wireless",
    label: "Wireless",
    summary: "Wireless gaming design candidate with supporting product video for sourcing review.",
    specs: ["Wireless direction", "OEM discussion available", "Video candidate available"],
    images: ["image-01.jpg", "image-02.jpg", "image-03.jpg"],
    folder: "g926-wireless",
    video: null
  },
  {
    model: "G921",
    name: "Wireless Gaming Headset",
    category: "wireless",
    label: "Wireless",
    summary: "Wireless headset direction for buyers expanding gaming accessory price points.",
    specs: ["Wireless direction", "Retail assortment review", "Commercial terms on request"],
    images: ["image-01.jpg", "image-02.jpg"],
    folder: "g921-wireless",
    video: null,
    public: false
  },
  {
    model: "G919",
    name: "Wireless Gaming Headset",
    category: "wireless",
    label: "Wireless",
    summary: "Wireless gaming headset candidate for value-focused assortment planning.",
    specs: ["Wireless direction", "Private-label discussion", "Specification on request"],
    images: ["image-01.jpg", "image-02.jpg"],
    folder: "g919-wireless",
    video: null,
    public: false
  },
  {
    model: "G938",
    name: "Wireless Gaming Headset",
    category: "wireless",
    label: "Wireless",
    summary: "Gaming headset visual direction prepared for wireless product evaluation.",
    specs: ["Wireless direction to confirm", "Color options shown", "Commercial terms on request"],
    images: ["image-01.png", "image-02.jpg", "image-03.png"],
    folder: "g938-wireless",
    video: null
  },
  {
    model: "G935",
    name: "Wireless Gaming Headset",
    category: "wireless",
    label: "Wireless",
    summary: "Clean wireless gaming headset direction with RGB accent styling for channel selection.",
    specs: ["Wireless configuration to confirm", "Boom microphone", "OEM branding discussion"],
    images: ["image-01.jpg", "image-02.jpg", "image-03.jpg", "image-04.jpg"],
    folder: "g935-wireless",
    video: null
  },
  {
    model: "B7",
    name: "Bluetooth Over-Ear Headphone",
    category: "bluetooth",
    label: "Bluetooth Audio",
    summary: "Lifestyle over-ear audio direction for consumer electronics assortment enquiries.",
    specs: ["Bluetooth direction", "Over-ear design", "Configuration to confirm"],
    images: ["image-01.jpg", "image-02.jpg", "image-03.jpg", "image-04.jpg"],
    folder: "b7-bluetooth",
    video: null
  },
  {
    model: "B9",
    name: "Bluetooth Over-Ear Headphone",
    category: "bluetooth",
    label: "Bluetooth Audio",
    summary: "Modern Bluetooth over-ear headphone direction for lifestyle audio assortments.",
    specs: ["Bluetooth audio", "Foldable-style over-ear design", "Color options shown"],
    images: ["image-01.jpg", "image-02.jpg", "image-03.jpg"],
    folder: "b9-bluetooth",
    video: null
  },
  {
    model: "B10",
    name: "Bluetooth Over-Ear Headphone",
    category: "bluetooth",
    label: "Bluetooth Audio",
    summary: "Clean Bluetooth headphone direction for retail and private-label audio programmes.",
    specs: ["Bluetooth audio", "Over-ear design", "OEM branding discussion"],
    images: ["image-01.jpg", "image-02.jpg", "image-03.jpg", "image-04.jpg"],
    folder: "b10-bluetooth",
    video: null
  },
  {
    model: "G946",
    name: "RGB Gaming Concept",
    category: "new",
    label: "New Design",
    summary: "High-impact RGB over-ear gaming visual. Specifications must be confirmed before sale.",
    specs: ["RGB visual design", "Boom microphone", "Details pending confirmation"],
    images: ["image-01.jpg", "image-02.jpg", "image-03.jpg", "image-04.jpg", "image-05.jpg", "image-06.jpg", "image-07.jpg", "image-08.jpg", "image-09.jpg", "image-10.jpg", "image-11.jpg", "image-12.jpg", "image-13.jpg", "image-14.jpg", "image-15.jpg", "image-16.jpg", "image-17.jpg", "image-18.jpg"],
    folder: "g946-rgb",
    video: null
  },
  {
    model: "G947",
    name: "New Gaming Headset Concept",
    category: "new",
    label: "New Design",
    summary: "New-design headset visual candidate for upcoming product selection.",
    specs: ["New design candidate", "Specifications on request", "Availability to confirm"],
    images: ["image-01.jpg", "image-02.jpg", "image-03.jpg"],
    folder: "g947-new",
    video: null
  },
  {
    model: "G942",
    name: "RGB Wired Gaming Headset",
    category: "wired",
    label: "Wired RGB",
    summary: "Illuminated wired gaming model for distributors seeking value-focused shelf impact.",
    specs: ["3.5 mm + USB interface listed", "20 Hz - 20 kHz", "Detachable microphone listed"],
    images: ["image-01.png", "image-02.png", "image-03.png", "image-04.jpg"],
    folder: "g942-wired",
    video: null
  },
  {
    model: "G935",
    name: "RGB Wired Gaming Headset",
    category: "wired",
    label: "Wired RGB",
    summary: "RGB wired design with demonstration footage for buyer product review.",
    specs: ["3.5 mm + USB interface listed", "Detachable microphone listed", "Video candidate available"],
    images: ["image-01.jpg", "image-02.jpg"],
    folder: "g935-wired",
    video: null
  },
  {
    model: "G936",
    name: "RGB Wired Gaming Headset",
    category: "wired",
    label: "Wired RGB",
    summary: "Wired gaming headset design with RGB lighting direction and OEM potential.",
    specs: ["3.5 mm + USB interface listed", "Detachable microphone listed", "Commercial terms on request"],
    images: ["image-01.jpg", "image-02.jpg"],
    folder: "g936-wired",
    video: null
  },
  {
    model: "G939",
    name: "RGB Wired Gaming Headset",
    category: "wired",
    label: "Wired RGB",
    summary: "Wired model for price-sensitive gaming accessory ranges and private label discussion.",
    specs: ["3.5 mm + USB interface listed", "Dynamic RGB listed", "OEM inquiry supported"],
    images: ["image-01.jpg", "image-02.jpg", "image-03.jpg", "image-04.jpg", "image-05.jpg", "image-06.jpg"],
    folder: "g939-wired",
    video: null
  },
  {
    model: "G923",
    name: "RGB Wired Gaming Headset",
    category: "wired",
    label: "Wired RGB",
    summary: "RGB wired model for value gaming programmes and branded packaging enquiries.",
    specs: ["3.5 mm + USB interface listed", "Dynamic RGB listed", "Specification sheet on request"],
    images: ["image-01.jpg", "image-02.jpg", "image-03.jpg", "image-04.jpg"],
    folder: "g923-wired",
    video: null
  },
  {
    model: "G941",
    name: "Wired Gaming Visual Candidate",
    category: "wired",
    label: "Wired",
    summary: "Product image set available; final wired configuration requires confirmation.",
    specs: ["Configuration to confirm", "OEM inquiry supported", "Not yet quoted"],
    images: ["image-01.jpg", "image-02.jpg"],
    folder: "g941-wired",
    video: null
  },
  {
    model: "G920",
    name: "Wired Gaming Headset",
    category: "wired",
    label: "Wired",
    summary: "Wired gaming headset direction for entry and promotional channel assortments.",
    specs: ["Wired configuration", "Boom microphone", "Commercial terms on request"],
    images: ["image-01.jpg", "image-02.jpg", "image-03.jpg", "image-04.jpg"],
    folder: "g920-wired",
    video: null,
    public: false
  },
  {
    model: "G926",
    name: "Wired Gaming Headset",
    category: "wired",
    label: "Wired",
    summary: "Wired headset candidate for private-label gaming product selection.",
    specs: ["Wired configuration", "Boom microphone", "Specification on request"],
    images: ["image-01.jpg", "image-02.jpg", "image-03.jpg", "image-04.jpg"],
    folder: "g926-wired",
    video: null,
    public: false
  },
  {
    model: "G921",
    name: "Wired Gaming Headset",
    category: "wired",
    label: "Wired",
    summary: "Wired gaming headset direction for value-led distribution enquiries.",
    specs: ["Wired configuration", "Product finish shown", "OEM discussion available"],
    images: ["image-01.jpg", "image-02.jpg"],
    folder: "g921-wired",
    video: null
  },
  {
    model: "G919",
    name: "Wired Gaming Headset",
    category: "wired",
    label: "Wired",
    summary: "Wired headset option for gaming accessory programme planning.",
    specs: ["Wired configuration", "Boom microphone", "Specification on request"],
    images: ["image-01.jpg", "image-02.jpg"],
    folder: "g919-wired",
    video: null
  },
  {
    model: "G907",
    name: "Wired Gaming Headset",
    category: "wired",
    label: "Wired",
    summary: "Wired gaming design for price-focused retail and wholesale evaluation.",
    specs: ["Wired configuration", "Color variants shown", "Commercial terms on request"],
    images: ["image-01.jpg", "image-02.jpg", "image-03.jpg"],
    folder: "g907-wired",
    video: null
  },
  {
    model: "G909",
    name: "Wired Gaming Headset",
    category: "wired",
    label: "Wired",
    summary: "Wired gaming headset reference for buyer sourcing discussions.",
    specs: ["Wired configuration", "Additional imagery on request", "Availability to confirm"],
    images: ["image-01.jpg"],
    folder: "g909-wired",
    video: null,
    public: false
  }
];
